version: '3.1'

services:
    nginx:
        image: nginx:1.15
        container_name: nginx
        volumes:
            - ../:/var/www
            - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - my-network
        depends_on:
            - server
            - client
    client:
        build:
            context: ../client
            dockerfile: Dockerfile
        container_name: client
        command: npm start
        volumes:
            - ../client:/usr/app
            - /usr/app/node_modules
        networks:
            my-network:
                aliases:
                    - client
        command: npm start
        stdin_open: true
        ports:
            - "3000:3000"
networks:
    my-network: